export const SET_CURRENT_COMPONENT = 'SET_CURRENT_COMPONENT';

export const MAIN_FORM = 'MAIN_FORM';
export const RESULT_PAGE = 'RESULT_PAGE';
export const ORDER_PAGE = 'ORDER_PAGE';

export const SET_MATERIAL = 'SET_MATERIAL';
export const SET_MATERIAL_TYPE = 'SET_MATERIAL_TYPE';

export const SET_MATERIAL_WEIGHT = 'SET_MATERIAL_WEIGHT';
export const SET_MATERIAL_VOLUME = 'SET_MATERIAL_VOLUME';

export const SET_DELIVERY_DATE = 'SET_DELIVERY_DATE';
export const SET_DELIVERY_TIME = 'SET_DELIVERY_TIME';
export const SET_PHONE_ON_UNLOADING = 'SET_PHONE_ON_UNLOADING';
export const SET_ORDER_COMMENT = 'SET_ORDER_COMMENT';

export const SET_CUSTOMER_NAME = 'SET_CUSTOMER_NAME';
export const SET_CUSTOMER_ORGANIZATION = 'SET_CUSTOMER_ORGANIZATION';
export const SET_CUSTOMER_PHONE = 'SET_CUSTOMER_PHONE';
export const SET_CUSTOMER_PAYMENT_METHOD = 'SET_CUSTOMER_PAYMENT_METHOD';
export const SET_CUSTOMER_ADDRESS = 'SET_CUSTOMER_ADDRESS';

// mobile
export const SET_CURRENT_MOBILE_COMPONENT = 'SET_CURRENT_MOBILE_COMPONENT';
export const ANKETA_PAGE = 'ANKETA_PAGE';
export const VYBOR_TOVARA_PAGE = 'VYBOR_TOVARA_PAGE';
export const CALCULATOR_PAGE = 'CALCULATOR_PAGE';
export const MAP_PAGE = 'MAP_PAGE';
export const PAYMENT_METHOD_PAGE = 'PAYMENT_METHOD_PAGE';
export const RESULT_MOBILE_PAGE = 'RESULT_MOBILE_PAGE';
export const ORDER_MOBILE_PAGE = 'ORDER_PAGE';
export const FINAL_PAGE = 'FINAL_PAGE';
